import { db, xeroSettingsTable } from "@workspace/db";
import { and, eq } from "drizzle-orm";

export const XERO_AUTHORIZE_URL = "https://login.xero.com/identity/connect/authorize";
export const XERO_TOKEN_URL = "https://identity.xero.com/connect/token";
export const XERO_CONNECTIONS_URL = "https://api.xero.com/connections";
export const XERO_ACCOUNTING_BASE_URL = "https://api.xero.com/api.xro/2.0";
export const XERO_SCOPES = "offline_access accounting.contacts accounting.invoices accounting.payments.read accounting.settings.read";

export type XeroTokenResponse = {
  access_token: string;
  refresh_token?: string;
  expires_in?: number;
  scope?: string;
};

export type XeroConnection = {
  id?: string;
  tenantId: string;
  tenantName?: string;
  tenantType?: string;
};

export type XeroSettingsRow = typeof xeroSettingsTable.$inferSelect;

export function getXeroClientId() {
  return process.env.XERO_CLIENT_ID?.trim() || "";
}

export function getXeroClientSecret() {
  return process.env.XERO_CLIENT_SECRET?.trim() || "";
}

export function getXeroRedirectUri() {
  return process.env.XERO_REDIRECT_URI?.trim() || "";
}

export function isXeroPlatformConfigured() {
  return Boolean(getXeroClientId() && getXeroClientSecret() && getXeroRedirectUri());
}

export function requireXeroPlatformConfigured() {
  if (!isXeroPlatformConfigured()) {
    throw new Error("Xero platform OAuth is not configured. Add XERO_CLIENT_ID, XERO_CLIENT_SECRET, and XERO_REDIRECT_URI in Render.");
  }
}

export async function getOrCreateXeroSettings(companyId: number) {
  const [existing] = await db
    .select()
    .from(xeroSettingsTable)
    .where(eq(xeroSettingsTable.companyId, companyId));
  if (existing) return existing;

  const [created] = await db.insert(xeroSettingsTable).values({
    companyId,
    connected: false,
    invoicePrefix: "INV",
    autoGenerateDay: 4,
  }).returning();
  return created;
}

export async function getStoredXeroSettings(companyId: number) {
  const [settings] = await db
    .select()
    .from(xeroSettingsTable)
    .where(eq(xeroSettingsTable.companyId, companyId));
  return settings ?? null;
}

export function serializeXeroSettings(settings: XeroSettingsRow) {
  return {
    id: settings.id,
    connected: settings.connected,
    tenantId: settings.tenantId,
    tenantName: settings.tenantName,
    invoicePrefix: settings.invoicePrefix,
    defaultAccountCode: settings.defaultAccountCode,
    autoGenerateDay: settings.autoGenerateDay,
    lastSyncAt: settings.lastSyncAt,
    platformConfigured: isXeroPlatformConfigured(),
  };
}

export async function exchangeCodeForXeroTokens(code: string) {
  requireXeroPlatformConfigured();

  const response = await fetch(XERO_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${Buffer.from(`${getXeroClientId()}:${getXeroClientSecret()}`).toString("base64")}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: getXeroRedirectUri(),
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero token exchange failed: ${text}`);
  }

  return (await response.json()) as XeroTokenResponse;
}

export async function fetchXeroConnections(accessToken: string) {
  const response = await fetch(XERO_CONNECTIONS_URL, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero connections lookup failed: ${text}`);
  }

  return (await response.json()) as XeroConnection[];
}

export async function refreshXeroAccessToken(settings: XeroSettingsRow) {
  requireXeroPlatformConfigured();
  if (!settings.refreshToken) {
    throw new Error("Xero is not connected. Connect Xero from Settings.");
  }

  const response = await fetch(XERO_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${Buffer.from(`${getXeroClientId()}:${getXeroClientSecret()}`).toString("base64")}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: settings.refreshToken,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero token refresh failed: ${text}`);
  }

  const token = (await response.json()) as XeroTokenResponse;
  const [updated] = await db
    .update(xeroSettingsTable)
    .set({
      accessToken: token.access_token,
      refreshToken: token.refresh_token ?? settings.refreshToken,
      tokenExpiresAt: new Date(Date.now() + (token.expires_in ?? 1800) * 1000),
      tokenScope: token.scope ?? settings.tokenScope ?? null,
    })
    .where(and(eq(xeroSettingsTable.id, settings.id), eq(xeroSettingsTable.companyId, settings.companyId ?? 0)))
    .returning();

  return updated;
}

export async function getUsableXeroSettings(companyId: number) {
  let settings = await getStoredXeroSettings(companyId);
  if (!settings?.connected || !settings.tenantId) {
    throw new Error("Xero is not connected. Connect Xero from Settings.");
  }

  const expiresAt = settings.tokenExpiresAt?.getTime() ?? 0;
  if (!settings.accessToken || expiresAt < Date.now() + 120_000) {
    settings = await refreshXeroAccessToken(settings);
  }

  if (!settings.accessToken || !settings.tenantId) {
    throw new Error("Xero connection is missing an access token or tenant.");
  }

  return settings;
}

async function callXero<T>(settings: XeroSettingsRow, path: string, init: RequestInit = {}) {
  if (!settings.accessToken || !settings.tenantId) {
    throw new Error("Xero connection is missing an access token or tenant.");
  }

  const url = path.startsWith("https://") ? path : `${XERO_ACCOUNTING_BASE_URL}${path}`;
  const response = await fetch(url, {
    ...init,
    headers: {
      Accept: "application/json",
      Authorization: `Bearer ${settings.accessToken}`,
      "xero-tenant-id": settings.tenantId,
      ...(init.body ? { "Content-Type": "application/json" } : {}),
      ...(init.headers ?? {}),
    },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero API request failed (${response.status}): ${text}`);
  }

  if (response.status === 204) return undefined as T;
  return (await response.json()) as T;
}

export async function xeroApi<T>(companyId: number, path: string, init: RequestInit = {}) {
  let settings = await getUsableXeroSettings(companyId);

  try {
    return {
      settings,
      data: await callXero<T>(settings, path, init),
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : "";
    if (!message.includes("401") && !message.toLowerCase().includes("unauthorized")) throw err;
    settings = await refreshXeroAccessToken(settings);
    return {
      settings,
      data: await callXero<T>(settings, path, init),
    };
  }
}
