import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customersRouter from "./customers";
import jobsRouter from "./jobs";
import invoicesRouter from "./invoices";
import appointmentsRouter from "./appointments";
import dashboardRouter from "./dashboard";
import subcontractorsRouter from "./subcontractors";
import workSessionsRouter from "./work-sessions";
import gpsRouter from "./gps";
import dispatchRouter from "./dispatch";
import jobReportsRouter from "./job-reports";
import stockItemsRouter from "./stock-items";
import xeroRouter from "./xero";
import weeklyInvoicesRouter from "./weekly-invoices";
import adminRouter from "./admin";
import analyticsRouter from "./analytics";
import bonusesRouter from "./bonuses";
import docketsRouter from "./dockets";
import inventoryRouter from "./inventory";
import aiAuditRouter from "./ai-audit";
import awardsRouter from "./awards";
import workerProfilesRouter from "./worker-profiles";
import leaveRequestsRouter from "./leave-requests";
import builderProfilesRouter from "./builder-profiles";
import smartAllocationRouter from "./smart-allocation";
import suppliersRouter from "./suppliers";
import profitabilityRouter from "./profitability";
import notificationsRouter from "./notifications";
import locationVerificationsRouter from "./location-verifications";
import staffInvitesRouter from "./staff-invites";
import { requireAuth, requireCompany, workerApiScope } from "../lib/auth.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(requireAuth);
router.use(requireCompany);
router.use(workerApiScope);
router.use(dashboardRouter);
router.use(customersRouter);
router.use(jobsRouter);
router.use(invoicesRouter);
router.use(appointmentsRouter);
router.use(subcontractorsRouter);
router.use(workSessionsRouter);
router.use(gpsRouter);
router.use(dispatchRouter);
router.use(jobReportsRouter);
router.use(stockItemsRouter);
router.use(xeroRouter);
router.use(weeklyInvoicesRouter);
router.use(adminRouter);
router.use(analyticsRouter);
router.use(bonusesRouter);
router.use(docketsRouter);
router.use(inventoryRouter);
router.use(aiAuditRouter);
router.use(awardsRouter);
router.use(workerProfilesRouter);
router.use(leaveRequestsRouter);
router.use(builderProfilesRouter);
router.use(smartAllocationRouter);
router.use(suppliersRouter);
router.use(profitabilityRouter);
router.use(notificationsRouter);
router.use(locationVerificationsRouter);
router.use(staffInvitesRouter);

export default router;
