import { Router } from "express";
import { db } from "@workspace/db";
import { xeroSettingsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { UpdateXeroSettingsBody } from "@workspace/api-zod";

const router = Router();

async function getOrCreateSettings() {
  const [existing] = await db.select().from(xeroSettingsTable);
  if (existing) return existing;
  const [created] = await db.insert(xeroSettingsTable).values({
    connected: false,
    invoicePrefix: "DS",
    autoGenerateDay: 4,
  }).returning();
  return created;
}

router.get("/xero/settings", async (req, res) => {
  const settings = await getOrCreateSettings();
  return res.json(settings);
});

router.patch("/xero/settings", async (req, res) => {
  const parsed = UpdateXeroSettingsBody.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "Invalid body" });

  const settings = await getOrCreateSettings();
  const updates: Record<string, unknown> = {};
  if (parsed.data.clientId !== undefined) updates.clientId = parsed.data.clientId;
  if (parsed.data.invoicePrefix !== undefined) updates.invoicePrefix = parsed.data.invoicePrefix;
  if (parsed.data.defaultAccountCode !== undefined) updates.defaultAccountCode = parsed.data.defaultAccountCode;
  if (parsed.data.autoGenerateDay !== undefined) updates.autoGenerateDay = parsed.data.autoGenerateDay;
  if (parsed.data.tenantName !== undefined) updates.tenantName = parsed.data.tenantName;

  const [updated] = await db.update(xeroSettingsTable).set(updates).where(eq(xeroSettingsTable.id, settings.id)).returning();
  return res.json(updated);
});

router.post("/xero/connect", async (req, res) => {
  const authUrl = "https://login.xero.com/identity/connect/authorize?response_type=code&client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&scope=openid profile email accounting.transactions accounting.contacts offline_access&state=diamond-sealing";
  return res.json({ authUrl });
});

router.post("/xero/disconnect", async (req, res) => {
  const settings = await getOrCreateSettings();
  const [updated] = await db.update(xeroSettingsTable).set({
    connected: false,
    tenantId: null,
    lastSyncAt: null,
  }).where(eq(xeroSettingsTable.id, settings.id)).returning();
  return res.json(updated);
});

export default router;
