import { Router } from "express";
import { randomBytes } from "node:crypto";
import { db } from "@workspace/db";
import { xeroSettingsTable } from "@workspace/db";
import { and, eq } from "drizzle-orm";
import { UpdateXeroSettingsBody } from "@workspace/api-zod";
import { companyId, requireAdmin } from "../lib/auth.js";

const router = Router();
const XERO_TOKEN_URL = "https://identity.xero.com/connect/token";
const XERO_CONNECTIONS_URL = "https://api.xero.com/connections";
const XERO_STATE_COOKIE = "ds_xero_state";

async function getOrCreateSettings(tenantId: number) {
  const [existing] = await db
    .select()
    .from(xeroSettingsTable)
    .where(eq(xeroSettingsTable.companyId, tenantId));
  if (existing) return existing;
  const [created] = await db.insert(xeroSettingsTable).values({
    companyId: tenantId,
    connected: false,
    invoicePrefix: "DS",
    autoGenerateDay: 4,
  }).returning();
  return created;
}

function getXeroClientId(settings: typeof xeroSettingsTable.$inferSelect) {
  return process.env.XERO_CLIENT_ID?.trim() || settings.clientId?.trim() || "";
}

function getXeroRedirectUri() {
  return process.env.XERO_REDIRECT_URI?.trim() || "";
}

function getXeroClientSecret() {
  return process.env.XERO_CLIENT_SECRET?.trim() || "";
}

function serializeSettings(settings: typeof xeroSettingsTable.$inferSelect) {
  const { accessToken: _accessToken, refreshToken: _refreshToken, ...safeSettings } = settings;
  return {
    ...safeSettings,
    clientId: getXeroClientId(settings) || settings.clientId,
    xeroOAuthReady: Boolean(getXeroClientId(settings) && getXeroRedirectUri() && getXeroClientSecret()),
    redirectUriConfigured: Boolean(getXeroRedirectUri()),
    redirectUri: getXeroRedirectUri() || null,
    clientSecretConfigured: Boolean(getXeroClientSecret()),
  };
}

type XeroTokenResponse = {
  access_token: string;
  refresh_token?: string;
  expires_in?: number;
  scope?: string;
};

type XeroConnection = {
  tenantId: string;
  tenantName?: string;
};

async function exchangeCodeForTokens(code: string, settings: typeof xeroSettingsTable.$inferSelect) {
  const clientId = getXeroClientId(settings);
  const clientSecret = getXeroClientSecret();
  const redirectUri = getXeroRedirectUri();

  const response = await fetch(XERO_TOKEN_URL, {
    method: "POST",
    headers: {
      Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      redirect_uri: redirectUri,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero token exchange failed: ${text}`);
  }

  return (await response.json()) as XeroTokenResponse;
}

async function fetchXeroConnections(accessToken: string) {
  const response = await fetch(XERO_CONNECTIONS_URL, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Xero connections lookup failed: ${text}`);
  }

  return (await response.json()) as XeroConnection[];
}

router.get("/xero/settings", requireAdmin, async (req, res) => {
  const settings = await getOrCreateSettings(companyId(req));
  return res.json(serializeSettings(settings));
});

router.patch("/xero/settings", requireAdmin, async (req, res) => {
  const parsed = UpdateXeroSettingsBody.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: "Invalid body" });

  const settings = await getOrCreateSettings(companyId(req));
  const updates: Record<string, unknown> = {};
  if (parsed.data.clientId !== undefined) updates.clientId = parsed.data.clientId;
  if (parsed.data.invoicePrefix !== undefined) updates.invoicePrefix = parsed.data.invoicePrefix;
  if (parsed.data.defaultAccountCode !== undefined) updates.defaultAccountCode = parsed.data.defaultAccountCode;
  if (parsed.data.autoGenerateDay !== undefined) updates.autoGenerateDay = parsed.data.autoGenerateDay;
  if (parsed.data.tenantName !== undefined) updates.tenantName = parsed.data.tenantName;

  const [updated] = await db
    .update(xeroSettingsTable)
    .set(updates)
    .where(and(eq(xeroSettingsTable.id, settings.id), eq(xeroSettingsTable.companyId, companyId(req))))
    .returning();
  return res.json(serializeSettings(updated));
});

router.post("/xero/connect", requireAdmin, async (req, res) => {
  const settings = await getOrCreateSettings(companyId(req));
  const clientId = getXeroClientId(settings);
  const redirectUri = getXeroRedirectUri();
  const clientSecret = getXeroClientSecret();

  if (!clientId || !redirectUri || !clientSecret) {
    return res.status(400).json({
      error: "Xero connection is not configured",
      message: "Set Xero Client ID, XERO_CLIENT_SECRET, and XERO_REDIRECT_URI before connecting.",
    });
  }

  const state = randomBytes(24).toString("base64url");
  res.cookie(XERO_STATE_COOKIE, state, {
    httpOnly: true,
    maxAge: 1000 * 60 * 10,
    path: "/",
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
  });

  const params = new URLSearchParams({
    response_type: "code",
    client_id: clientId,
    redirect_uri: redirectUri,
    scope: "openid profile email accounting.transactions accounting.contacts offline_access",
    state,
  });
  const authUrl = `https://login.xero.com/identity/connect/authorize?${params.toString()}`;
  return res.json({ authUrl });
});

router.get("/xero/callback", requireAdmin, async (req, res) => {
  const code = typeof req.query.code === "string" ? req.query.code : "";
  const error = typeof req.query.error === "string" ? req.query.error : "";
  const state = typeof req.query.state === "string" ? req.query.state : "";
  const expectedState = typeof req.cookies?.[XERO_STATE_COOKIE] === "string" ? req.cookies[XERO_STATE_COOKIE] : "";

  res.clearCookie(XERO_STATE_COOKIE, {
    path: "/",
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
  });

  if (error) {
    return res.redirect(`/settings/xero?xero=error&message=${encodeURIComponent(error)}`);
  }

  if (!state || !expectedState || state !== expectedState) {
    return res.redirect("/settings/xero?xero=error&message=Invalid%20Xero%20connection%20state");
  }

  if (!code) {
    return res.redirect("/settings/xero?xero=error&message=Missing%20Xero%20authorization%20code");
  }

  try {
    const settings = await getOrCreateSettings(companyId(req));
    const token = await exchangeCodeForTokens(code, settings);
    const connections = await fetchXeroConnections(token.access_token);
    const connection = connections[0];

    if (!connection?.tenantId) {
      throw new Error("Xero did not return a connected tenant.");
    }

    await db.update(xeroSettingsTable).set({
      connected: true,
      tenantId: connection.tenantId,
      tenantName: connection.tenantName ?? settings.tenantName ?? null,
      accessToken: token.access_token,
      refreshToken: token.refresh_token ?? settings.refreshToken ?? null,
      tokenExpiresAt: new Date(Date.now() + (token.expires_in ?? 1800) * 1000),
      tokenScope: token.scope ?? null,
      lastSyncAt: new Date(),
    }).where(and(eq(xeroSettingsTable.id, settings.id), eq(xeroSettingsTable.companyId, companyId(req))));

    return res.redirect("/settings/xero?xero=connected");
  } catch (err) {
    req.log.error({ err }, "Xero callback failed");
    const message = err instanceof Error ? err.message : "Xero connection failed";
    return res.redirect(`/settings/xero?xero=error&message=${encodeURIComponent(message)}`);
  }
});

router.post("/xero/disconnect", requireAdmin, async (req, res) => {
  const settings = await getOrCreateSettings(companyId(req));
  const [updated] = await db.update(xeroSettingsTable).set({
    connected: false,
    tenantId: null,
    accessToken: null,
    refreshToken: null,
    tokenExpiresAt: null,
    tokenScope: null,
    lastSyncAt: null,
  }).where(and(eq(xeroSettingsTable.id, settings.id), eq(xeroSettingsTable.companyId, companyId(req)))).returning();
  return res.json(serializeSettings(updated));
});

export default router;
