import { useState, useEffect } from "react";
import { useGetXeroSettings, useUpdateXeroSettings, useConnectXero, useDisconnectXero } from "@workspace/api-client-react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertTriangle, CheckCircle2, Info, Plug, RefreshCw, Receipt, Unplug, Users } from "lucide-react";

async function postXeroAction<T>(path: string): Promise<T> {
  const response = await fetch(path, { method: "POST" });
  const data = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(data?.message || data?.error || "Xero action failed");
  }
  return data as T;
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message.replace(/^HTTP 400 Bad Request:\s*/i, "") : "Try again.";
}

export default function XeroSettings() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data: settings, isLoading } = useGetXeroSettings();
  const platformConfigured = Boolean((settings as any)?.platformConfigured);

  const [invoicePrefix, setInvoicePrefix] = useState("INV");
  const [defaultAccountCode, setDefaultAccountCode] = useState("200");
  const [autoGenerateDay, setAutoGenerateDay] = useState("4");
  const [connectionMessage, setConnectionMessage] = useState("");

  useEffect(() => {
    if (settings) {
      setInvoicePrefix(settings.invoicePrefix || "INV");
      setDefaultAccountCode(settings.defaultAccountCode || "200");
      setAutoGenerateDay(settings.autoGenerateDay?.toString() || "4");
    }
  }, [settings]);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const xero = params.get("xero");
    if (xero === "connected") {
      toast({ title: "Xero connected" });
      queryClient.invalidateQueries();
      window.history.replaceState(null, "", "/settings/xero");
    }
    if (xero === "error") {
      const message = params.get("message") || "Xero connection failed.";
      setConnectionMessage(message);
      toast({ title: "Xero connection failed", description: message, variant: "destructive" });
      window.history.replaceState(null, "", "/settings/xero");
    }
  }, [queryClient, toast]);

  const updateSettings = useUpdateXeroSettings({
    mutation: {
      onSuccess: () => {
        setConnectionMessage("");
        toast({ title: "Settings saved" });
        queryClient.invalidateQueries();
      },
    },
  });

  const connectXero = useConnectXero({
    mutation: {
      onSuccess: (data) => {
        setConnectionMessage("");
        if (data.authUrl) {
          window.location.assign(data.authUrl);
          return;
        }
        const message = "Xero OAuth is not configured for this platform yet.";
        setConnectionMessage(message);
        toast({ title: "Xero connection not ready", description: message, variant: "destructive" });
      },
      onError: (error) => {
        const message = errorMessage(error);
        setConnectionMessage(message);
        toast({ title: "Xero connection not ready", description: message, variant: "destructive" });
      },
    },
  });

  const disconnectXero = useDisconnectXero({
    mutation: {
      onSuccess: () => {
        toast({ title: "Disconnected from Xero" });
        queryClient.invalidateQueries();
      },
      onError: (error) => {
        toast({ title: "Could not disconnect Xero", description: errorMessage(error), variant: "destructive" });
      },
    },
  });

  const testConnection = useMutation({
    mutationFn: () => postXeroAction<{ tenantName?: string | null; message?: string }>("/api/xero/test-connection"),
    onSuccess: (data) => {
      toast({ title: "Xero connection working", description: data.tenantName || data.message || undefined });
      queryClient.invalidateQueries();
    },
    onError: (error) => {
      toast({ title: "Xero test failed", description: errorMessage(error), variant: "destructive" });
    },
  });

  const syncContacts = useMutation({
    mutationFn: () => postXeroAction<{ total: number; synced: number; failed: number }>("/api/xero/sync-contacts"),
    onSuccess: (data) => {
      toast({ title: "Contacts synced", description: `${data.synced}/${data.total} contacts synced${data.failed ? `, ${data.failed} failed` : ""}.` });
      queryClient.invalidateQueries();
    },
    onError: (error) => {
      toast({ title: "Could not sync contacts", description: errorMessage(error), variant: "destructive" });
    },
  });

  const syncInvoices = useMutation({
    mutationFn: () => postXeroAction<{ syncedSalesInvoices: number; syncedWeeklyBills: number; failed: number }>("/api/xero/sync-invoices"),
    onSuccess: (data) => {
      toast({
        title: "Invoices synced",
        description: `${data.syncedSalesInvoices} sales invoice(s), ${data.syncedWeeklyBills} weekly bill(s) synced${data.failed ? `, ${data.failed} failed` : ""}.`,
      });
      queryClient.invalidateQueries();
    },
    onError: (error) => {
      toast({ title: "Could not sync invoices", description: errorMessage(error), variant: "destructive" });
    },
  });

  const handleSave = () => {
    updateSettings.mutate({
      data: {
        invoicePrefix,
        defaultAccountCode,
        autoGenerateDay: parseInt(autoGenerateDay),
      },
    });
  };

  const handleConnect = () => {
    if (!platformConfigured) {
      const message = "Xero platform OAuth is not configured yet. Add XERO_CLIENT_ID, XERO_CLIENT_SECRET, and XERO_REDIRECT_URI in Render.";
      setConnectionMessage(message);
      toast({ title: "Xero platform setup required", description: message, variant: "destructive" });
      return;
    }
    connectXero.mutate();
  };

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Xero Integration</h1>
        <p className="text-muted-foreground mt-2">Connect this company account to Xero and sync clients, invoices, and weekly bills.</p>
      </div>

      <div className="bg-orange-50 dark:bg-orange-950/30 text-orange-900 dark:text-orange-300 p-4 rounded-lg flex gap-3 text-sm">
        <Info className="h-5 w-5 shrink-0" />
        <p>
          Connect your Xero account to automatically sync customer details, invoices and payment status.
          <br />
          <br />
          Once connected, completed jobs can be sent directly to Xero, helping reduce admin time and keeping your accounts up to date.
        </p>
      </div>

      {!isLoading && !platformConfigured && (
        <div className="bg-amber-50 dark:bg-amber-950/30 text-amber-900 dark:text-amber-200 p-4 rounded-lg flex gap-3 text-sm border border-amber-200 dark:border-amber-800">
          <AlertTriangle className="h-5 w-5 shrink-0" />
          <p>{connectionMessage || "Xero platform OAuth is not configured yet. Add XERO_CLIENT_ID, XERO_CLIENT_SECRET, and XERO_REDIRECT_URI in Render."}</p>
        </div>
      )}

      {!isLoading && platformConfigured && !settings?.connected && connectionMessage && (
        <div className="bg-amber-50 dark:bg-amber-950/30 text-amber-900 dark:text-amber-200 p-4 rounded-lg flex gap-3 text-sm border border-amber-200 dark:border-amber-800">
          <AlertTriangle className="h-5 w-5 shrink-0" />
          <p>{connectionMessage}</p>
        </div>
      )}

      {isLoading ? (
        <Skeleton className="h-48 w-full" />
      ) : (
        <Card className={`border-2 ${settings?.connected ? "border-primary/50" : "border-dashed"}`}>
          <CardContent className="p-6 space-y-5">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
              <div className="flex items-start gap-4">
                <div className={`p-3 rounded-full ${settings?.connected ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>
                  {settings?.connected ? <CheckCircle2 className="h-8 w-8" /> : <Unplug className="h-8 w-8" />}
                </div>
                <div className="space-y-2">
                  <div>
                    <p className="text-sm text-muted-foreground">Connected to:</p>
                    <h3 className="text-lg font-bold">{settings?.connected ? settings.tenantName || "Xero organisation" : "Not connected"}</h3>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-muted-foreground">Status:</span>
                    <Badge variant={settings?.connected ? "default" : "outline"}>{settings?.connected ? "Connected" : "Not connected"}</Badge>
                  </div>
                  {settings?.connected && settings.lastSyncAt && (
                    <p className="text-muted-foreground text-xs">Last sync: {new Date(settings.lastSyncAt).toLocaleString()}</p>
                  )}
                </div>
              </div>

              {!settings?.connected ? (
                <Button onClick={handleConnect} disabled={connectXero.isPending || !platformConfigured}>
                  <Plug className="h-4 w-4 mr-2" /> {connectXero.isPending ? "Connecting..." : "Connect to Xero"}
                </Button>
              ) : (
                <Button variant="outline" className="text-destructive" onClick={() => { if (confirm("Disconnect Xero?")) disconnectXero.mutate(); }}>
                  <Unplug className="h-4 w-4 mr-2" /> Disconnect Xero
                </Button>
              )}
            </div>

            {settings?.connected && (
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <Button variant="outline" onClick={() => testConnection.mutate()} disabled={testConnection.isPending}>
                  <RefreshCw className="h-4 w-4 mr-2" /> Test Connection
                </Button>
                <Button variant="outline" onClick={() => syncContacts.mutate()} disabled={syncContacts.isPending}>
                  <Users className="h-4 w-4 mr-2" /> Sync Contacts
                </Button>
                <Button variant="outline" onClick={() => syncInvoices.mutate()} disabled={syncInvoices.isPending}>
                  <Receipt className="h-4 w-4 mr-2" /> Sync Invoices
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Invoice Mapping</CardTitle>
          <CardDescription>Default invoice settings for this company account</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label>Invoice Prefix</Label>
              <Input value={invoicePrefix} onChange={(e) => setInvoicePrefix(e.target.value)} placeholder="INV" />
            </div>

            <div className="space-y-2">
              <Label>Default Xero Account Code</Label>
              <Input value={defaultAccountCode} onChange={(e) => setDefaultAccountCode(e.target.value)} placeholder="200" />
            </div>

            <div className="space-y-2">
              <Label>Auto-Generate Day</Label>
              <Select value={autoGenerateDay} onValueChange={setAutoGenerateDay}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">Monday</SelectItem>
                  <SelectItem value="2">Tuesday</SelectItem>
                  <SelectItem value="3">Wednesday</SelectItem>
                  <SelectItem value="4">Thursday</SelectItem>
                  <SelectItem value="5">Friday</SelectItem>
                  <SelectItem value="6">Saturday</SelectItem>
                  <SelectItem value="0">Sunday</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
        <CardFooter className="border-t pt-6">
          <Button onClick={handleSave} disabled={updateSettings.isPending}>Save Settings</Button>
        </CardFooter>
      </Card>
    </div>
  );
}
