import { useState, useEffect } from "react";
import { useGetXeroSettings, useUpdateXeroSettings, useConnectXero, useDisconnectXero } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertTriangle, CheckCircle2, Info, Plug, Unplug } from "lucide-react";

export default function XeroSettings() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  
  const { data: settings, isLoading } = useGetXeroSettings();

  const [clientId, setClientId] = useState("");
  const [invoicePrefix, setInvoicePrefix] = useState("DS");
  const [defaultAccountCode, setDefaultAccountCode] = useState("200");
  const [autoGenerateDay, setAutoGenerateDay] = useState("4"); // 4 = Thursday
  const [tenantName, setTenantName] = useState("");

  useEffect(() => {
    if (settings) {
      setClientId(settings.clientId || "");
      setInvoicePrefix(settings.invoicePrefix || "DS");
      setDefaultAccountCode(settings.defaultAccountCode || "200");
      setAutoGenerateDay(settings.autoGenerateDay?.toString() || "4");
      setTenantName(settings.tenantName || "");
    }
  }, [settings]);

  const updateSettings = useUpdateXeroSettings({
    mutation: {
      onSuccess: () => {
        toast({ title: "Settings saved" });
        queryClient.invalidateQueries();
      }
    }
  });

  const connectXero = useConnectXero({
    mutation: {
      onSuccess: (data) => {
        // In a real app we'd redirect, here we just show the URL to the user for mockup
        alert(`In a real flow, you would be redirected to:\n${data.authUrl}`);
      }
    }
  });

  const disconnectXero = useDisconnectXero({
    mutation: {
      onSuccess: () => {
        toast({ title: "Disconnected from Xero" });
        queryClient.invalidateQueries();
      }
    }
  });

  const handleSave = () => {
    updateSettings.mutate({
      data: {
        clientId,
        invoicePrefix,
        defaultAccountCode,
        autoGenerateDay: parseInt(autoGenerateDay),
        tenantName
      }
    });
  };

  return (
    <div className="space-y-6 max-w-3xl">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Xero Integration</h1>
        <p className="text-muted-foreground mt-2">Connect Diamond Sealing to Xero to sync subcontractor invoices.</p>
      </div>

      <div className="bg-blue-50 dark:bg-blue-950/30 text-blue-800 dark:text-blue-300 p-4 rounded-lg flex gap-3 text-sm">
        <Info className="h-5 w-5 shrink-0" />
        <p>Diamond Sealing invoices are automatically prepared every Thursday evening, based on completed job reports for the week. Review and submit them from the Weekly Invoices page.</p>
      </div>

      {isLoading ? (
        <Skeleton className="h-48 w-full" />
      ) : (
        <Card className={`border-2 ${settings?.connected ? 'border-[#13B5EA]/50' : 'border-dashed'}`}>
          <CardContent className="p-6 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className={`p-3 rounded-full ${settings?.connected ? 'bg-[#13B5EA]/10 text-[#13B5EA]' : 'bg-muted text-muted-foreground'}`}>
                {settings?.connected ? <CheckCircle2 className="h-8 w-8" /> : <Unplug className="h-8 w-8" />}
              </div>
              <div>
                <h3 className="text-lg font-bold">{settings?.connected ? 'Connected to Xero' : 'Not Connected'}</h3>
                {settings?.connected && settings.tenantName && (
                  <p className="text-muted-foreground text-sm mt-1">Tenant: {settings.tenantName}</p>
                )}
                {settings?.connected && settings.lastSyncAt && (
                  <p className="text-muted-foreground text-xs mt-1">Last sync: {new Date(settings.lastSyncAt).toLocaleString()}</p>
                )}
              </div>
            </div>
            
            <div>
              {settings?.connected ? (
                <Button variant="outline" className="text-destructive" onClick={() => { if(confirm('Disconnect Xero?')) disconnectXero.mutate(); }}>
                  Disconnect
                </Button>
              ) : (
                <Button className="bg-[#13B5EA] hover:bg-[#0f92bd] text-white" onClick={() => connectXero.mutate()}>
                  <Plug className="h-4 w-4 mr-2" /> Connect to Xero
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Configuration</CardTitle>
          <CardDescription>Settings for how invoices map to your Xero account</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label>Client ID</Label>
              <Input value={clientId} onChange={e => setClientId(e.target.value)} placeholder="Xero OAuth Client ID" />
            </div>
            
            <div className="space-y-2">
              <Label>Tenant Name</Label>
              <Input value={tenantName} onChange={e => setTenantName(e.target.value)} placeholder="e.g. Diamond Sealing PTY LTD" />
            </div>

            <div className="space-y-2">
              <Label>Invoice Prefix</Label>
              <Input value={invoicePrefix} onChange={e => setInvoicePrefix(e.target.value)} placeholder="DS" />
              <p className="text-xs text-muted-foreground">Invoices will be created as DS-0001, etc.</p>
            </div>

            <div className="space-y-2">
              <Label>Default Account Code</Label>
              <Input value={defaultAccountCode} onChange={e => setDefaultAccountCode(e.target.value)} placeholder="200" />
              <p className="text-xs text-muted-foreground">The Xero Chart of Accounts code for expenses</p>
            </div>

            <div className="space-y-2">
              <Label>Auto-Generate Day</Label>
              <Select value={autoGenerateDay} onValueChange={setAutoGenerateDay}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">Monday</SelectItem>
                  <SelectItem value="2">Tuesday</SelectItem>
                  <SelectItem value="3">Wednesday</SelectItem>
                  <SelectItem value="4">Thursday</SelectItem>
                  <SelectItem value="5">Friday</SelectItem>
                  <SelectItem value="6">Saturday</SelectItem>
                  <SelectItem value="0">Sunday</SelectItem>
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">Day of week to prepare draft invoices</p>
            </div>
          </div>
        </CardContent>
        <CardFooter className="border-t pt-6">
          <Button onClick={handleSave} disabled={updateSettings.isPending}>Save Settings</Button>
        </CardFooter>
      </Card>
    </div>
  );
}