import { pgTable, serial, boolean, text, integer, timestamp } from "drizzle-orm/pg-core";
import { companyAccountsTable } from "./company-accounts";

export const xeroSettingsTable = pgTable("xero_settings", {
  id: serial("id").primaryKey(),
  companyId: integer("company_id").references(() => companyAccountsTable.id),
  connected: boolean("connected").notNull().default(false),
  tenantId: text("tenant_id"),
  tenantName: text("tenant_name"),
  clientId: text("client_id"),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  tokenExpiresAt: timestamp("token_expires_at", { withTimezone: true }),
  tokenScope: text("token_scope"),
  invoicePrefix: text("invoice_prefix").default("INV"),
  defaultAccountCode: text("default_account_code"),
  autoGenerateDay: integer("auto_generate_day").notNull().default(4),
  lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
});

export type XeroSettings = typeof xeroSettingsTable.$inferSelect;
