import { pgTable, serial, boolean, text, integer, timestamp } from "drizzle-orm/pg-core";

export const xeroSettingsTable = pgTable("xero_settings", {
  id: serial("id").primaryKey(),
  connected: boolean("connected").notNull().default(false),
  tenantId: text("tenant_id"),
  tenantName: text("tenant_name"),
  clientId: text("client_id"),
  invoicePrefix: text("invoice_prefix").default("DS"),
  defaultAccountCode: text("default_account_code"),
  autoGenerateDay: integer("auto_generate_day").notNull().default(4),
  lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
});

export type XeroSettings = typeof xeroSettingsTable.$inferSelect;
